name: Publish

on:
  push:
    tags:
      - '*.*.*'

env:
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Disable telemetry message
  DOTNET_NOLOGO: true
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Do not extract XML documentation files from nuget packages
  NUGET_XMLDOC_MODE: skip
  NETCORE_VERSION: '5.0.101'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'
  PROJECT_CONFIGURATION: Release
  PROJECT_PATH: ./src/PhoneNumbers/PhoneNumbers.csproj

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build ${{ env.PROJECT_CONFIGURATION }}
      run: dotnet build --configuration ${{ env.PROJECT_CONFIGURATION }} --no-restore

    - name: dotnet test
      run: dotnet test --no-restore --verbosity minimal

    - name: dotnet pack
      run: dotnet pack --no-build --configuration ${{ env.PROJECT_CONFIGURATION }}

    - name: dotnet nuget push
      run: dotnet nuget push '/home/runner/work/**/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SOURCE }}
